# Generated by Django 2.2.1 on 2019-06-22 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='image',
        ),
    ]
